Task-11
Kravchene/Java-Homework pull request #11
Opened 2023-03-16 16:23 UTC by Kravchene

2023-04-06 11:36 UTC, Willynick requested changes

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/WrongLoginException.java
> +public class WrongLoginException  extends Exception{
Ошиби лучше создавать в отедльных классах

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/WrongLoginException.java
> +class WrongPasswordException extends Exception{
Давай отправлять какое-то сообщение в ошибку, чтобы было понятно и мы смогли выводить информацию из этого сообщения в консоль

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/TheBestWebsite.java
> +    public static void main(String[] args) throws WrongLoginException {
Оооочень, прям ооочень большой метод main)
Давай мы его разобъем на маленькие методы. Причём бизнес-логику переноси в другие классы. Например логика по авторизации - AuthroizationService. Логика по регистрации - RegistrationService.

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/TheBestWebsite.java
> +    public static void main(String[] args) throws WrongLoginException {
Класс Main - у нас представительский - для взаимодействия с пользователем. Т.е. тупо ввод/вывод в консол и создание нужных объектов (например репозиторий).

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/TheBestWebsite.java
> +                        String regex = "^\\S[a-zA-Z\\d-_]{8,}\\S$";
У нас это по сути константа, но будет создаваться каждый раз. Константы можно выносить как статическое поле класса

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserRepository.java
> +public class UserRepository implements Cloneable {
UserRepository - класс, который должен содержать репозиторий, т.е. БД, т.е. список пользователей. Поэтому давай переделаем под эту логику

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserRepository.java
> +    public boolean equals1(Object o) {
Давай не будем писать equals1 2 3 и т.д.
Создай отдельные методы в каком-нибудь сервисном методе в классе AuthorizationService (RegistrationService)

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/TheBestWebsite.java
> +                UserRepository userRepository = new UserRepository(login1,password1);
Объект репозиторий - это объект, который должен быть один на всё приложение. Тоже самое, как с БД. На всю работу приложения у нас одни данные. Если мы будем создавать новый репозиторий каждый раз - пользователи, которые там будут храниться потеряются. А нам же нужно их сохранять

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserRepository.java
> +    public static List<UserRepository> user = new ArrayList<>();
Список пользователей храним. А тут список реопзиториев. Т.е. давай разделим и создадим отдельный класс User

2023-04-06 11:36 UTC, Willynick commented on src/by/itacademy/courses/hw11/TheBestWebsite.java
> +                    if (passwordVerification) {
Пустой блок if - такого не должно быть

2023-04-11 11:02 UTC, Willynick requested changes

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/CaseLogic/CaseLogic.java
> +package by.itacademy.courses.hw11.CaseLogic;
Пакеты (папки) стараемся называть следующим образом: 
word1.word2.word3 - т.е. всегда с маленькой буквы и слова разделяются точками

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserAccount.java
> +import java.util.ArrayList;
Неиспольземых два импорта

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserAccount.java
> +    public static boolean loginVerification(UserAccount a) {
Этот и ниже методы лучше вынести в сервис либо утилитарный клас со статическими методами и приватным конструктором

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserAccount.java
> +        boolean trueOrFalse = false;
Можно обойтись без переменной, а сразу return

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserRepository.java
> +    private static List<UserAccount> user = new ArrayList<>();
Здесь список пользователей, а не просто user. Давай соответствующе называть

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserRepository.java
> +    public static List<UserAccount> getUser() {
Тоже самое касается и метода. Также не стоит делать это статикой. Я бы лучше объект репозитория создал и им пользовался

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserAccount.java
> +    public static void repository(String a,String b) {
Логика по добавлению пользователя в репозиторий должна содержаться не в этом классе (класс модели), а в сервисном. Т.е. необходимо создать RegistrationService, например

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/CaseLogic/LogicCase1.java
> +public class LogicCase1 {
Я бы создал полноценные классы серсиво. AuthorizationService и RegistrationService

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/CaseLogic/LogicCase1.java
> +                String regex = "^\\S[a-zA-Z-_]{5,20}\\S$";
Можно вынести в константу (final) - поле на уровне класса

2023-04-11 11:02 UTC, Willynick commented on src/by/itacademy/courses/hw11/CaseLogic/LogicCase1.java
> +                System.out.print("Введите Логин: ");
Ввод/вывод - можно перетащить в main

2023-04-11 12:33 UTC, Kravchene commented on src/by/itacademy/courses/hw11/UserAccount.java
> +        boolean trueOrFalse = false;
![image](https://user-images.githubusercontent.com/123401951/231163415-6a940f70-50a6-4a14-842e-dcea4439ce1c.png)

2023-04-11 12:34 UTC, Kravchene commented on src/by/itacademy/courses/hw11/UserAccount.java
> +        boolean trueOrFalse = false;
ошибка тогда

2023-04-11 13:00 UTC, Kravchene commented on src/by/itacademy/courses/hw11/CaseLogic/LogicCase1.java
> +                System.out.print("Введите Логин: ");
как я потом передам как нужно будет я просто не понимаю

2023-04-17 08:25 UTC, Willynick commented on src/by/itacademy/courses/hw11/RegistrationService.java
> +    static UserRepository userRepository = new UserRepository();
Класс утилитарный. Он должен овтечать только за свою логику. Он не отвечает за создание репозитория

2023-04-17 08:25 UTC, Willynick commented on src/by/itacademy/courses/hw11/UserAccount.java
> +        boolean trueOrFalse = false;
return false написать можно просто последней инструкцией, но ладно

2023-04-17 08:28 UTC, Willynick requested changes

2023-04-17 08:28 UTC, Willynick commented on src/by/itacademy/courses/hw11/Verification.java
> +    static UserRepository userRepository = new UserRepository();
Необходимо создавать один пользовательский репозиторий на всё приложение. Иначе будет бардак - как понять, к какому репозиторию обращаться? Тем более нет в этом надобности

2023-04-17 08:28 UTC, Willynick commented on src/by/itacademy/courses/hw11/RegistrationService.java
> +    public static void repository(String a, String b) {
Лучше в сервисе (класс бищнес-логики) не делать статических методов

2023-04-17 08:28 UTC, merged