Task 4
Kravchene/Java-Homework pull request #4
Opened 2023-02-15 10:24 UTC by Kravchene

2023-02-18 15:30 UTC, Willynick requested changes

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task1.java
> +            int[] a = new int[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
Давай чисто циклами обойдёмся) очень большое решение для небольшой задачки

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task2.java
> +        System.out.print("введите число 1: ");
Найдите сумму и произведение цифр числа, введенного с клавиатуры.
Если мы говорим про число 125, необходимо найти 1 + 2 + 5 и 1 *2 * 5

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task3.java
> +        int n = in.nextInt();
Давай корректно называть перменные

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task3.java
> +    static int test(int n) {
И не забываем про корректное название функции)

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
> +    static void numberMinOrMax(int[] number){
А зачем эта функция если в main есть?

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
> +        for(int i=0;i < number.length;i++){
Слишком много циклов. Можно обойтись лишь одним для поиска мин и макс и их индексов (без bynarySearch)

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task5.java
> +            if (number[i] < minNumber && i%2!=0) {
условие i % 2 можно вывести в for, т.е. чтобы онн проходил только по нечётными (вместо инкремента написать i=i+2 например)

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task6.java
> +        int[] number1 =new int[8];
А если у нас изменится кол-во элементов в массиве?

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task6.java
> +        for (int i = 0; i<number1.length;i++){
По факту массивы содержат нули. Давай сделаем так, чтобы их там н ебыло

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task7.java
> +        number[0] = randomNumber.nextInt();
можно заполнить массив в цикле

2023-02-18 15:30 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task7.java
> +        for (int i= number.length-1;i>=0;i--){
По факту сам массив не изменился. Давай сделаем так, чтобы в нём элементы находились в обратном порядке

2023-02-20 09:46 UTC, Kravchene commented on src/by/itacademy/courses/hw4/Task5.java
> +            if (number[i] < minNumber && i%2!=0) {
не думал что так можно

2023-02-20 13:19 UTC, Willynick requested changes

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task1.java
>          }
Куда-то ухела фигурная скобочка. Перед ней пробелов быть не должно

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
>  package by.itacademy.courses.hw4;
После package должна быть пустая строчка

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
> +    public static void getMinOrMax(int[] number){
между функциями должна быть пустая строчка

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
> +
Зачем тут такое кол-во пустых строк в методе main?)

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
> +            index1 = i;}
Последняя фигурная скобочка должна быть на новой строке

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
> +                index2 = i;}}
Тоже самое. Каждая фигурная скобочка на своей конкретно строчке. В среде разрбаокте легко можно сделать выравнивание

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task6.java
> +        int[] positiveNumber = new int[positiveElements], negativeNumber = new int[negativeElements];
Слишком большая функция. По сути она состоит из нескольких составных частей:
Подсчет и формирование массивов, заполнение массивов, вывод массивов. 
И весь этот функционал можно поместить в разные и отдельные методы

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task7.java
> +import java.util.Arrays;
Неиспользуемый import. Не забываем за этим следить

2023-02-20 13:19 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task7.java
> +            int b = number[i];
Не понимаю, что значит буква b)
Давай нормально назовём

2023-02-20 13:32 UTC, Kravchene commented on src/by/itacademy/courses/hw4/Task4.java
> +                index2 = i;}}
мне просто так удобнее смотреть за кодом я думал  это некритично

2023-02-22 12:35 UTC, Willynick requested changes

2023-02-22 12:35 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task6.java
> +public class Task6 {
Необходимо пустая строчка после package и посмотри пожалуйста везде чтобы так было

2023-02-22 12:36 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task6.java
> +        int[] positiveNumber = new int[positiveElements], negativeNumber = new int[negativeElements];
Не забудь про разбивку на методы)

2023-03-02 11:58 UTC, merged