Task6
Kravchene/Java-Homework pull request #6
Opened 2023-02-23 10:51 UTC by Kravchene

2023-03-07 22:38 UTC, Willynick requested changes

2023-03-07 22:38 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task1.java
> +    static void adjustment(String text){
Пробельчик между скобочками

2023-03-07 22:38 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task2.java
> +        String maxNumber = new String();
new String() инициализация не обязательна

2023-03-07 22:38 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task3.java
> +        static void replacement (String text,int indexMax,int indexMin,String regex){
Разобраться с форматированием

2023-03-07 22:38 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task3.java
> +        for (String text2 : words){
Можно написать отдельную функцию для формирования результата. Так будет нагляднее

2023-03-07 22:38 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task4.java
> +        StringBuilder str1 = new StringBuilder();
Создай один StringBuilder на все случаи. Разделяй с помощью /n их просто

2023-03-07 22:38 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task5.java
> +        String str1 = "Object-oriented programming";
Давай давать более информативные названия переменных

2023-03-07 22:38 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task5.java
> +    static void editor(String text,String str1,String str2) {
Не совсем правильный алгоритм. 
![image](https://user-images.githubusercontent.com/57830441/223569876-ea76d40d-0591-4981-828e-c51a115cb72f.png)

2023-03-22 13:32 UTC, Willynick requested changes

2023-03-22 13:32 UTC, Willynick commented on src/by/itacademy/courses/hw6/Task5.java
> +        int i = 0;
Что-то с форматированием

2023-03-22 13:55 UTC, Kravchene commented on src/by/itacademy/courses/hw6/Task1.java
> +    static void adjustment(String text){
его там нет

2023-03-23 08:33 UTC, merged